name: Docker Validation

on:
  push:
    branches:
      - main
      - developer

jobs:
  validate-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Set permissions for Maven Wrapper
        run: chmod +x ./backend/mvnw

      - name: Clear Maven Cache
        run: |
          cd backend
          ./mvnw clean install -U
          cd ..

      - name: Build JAR file
        run: |
          cd backend
          ./mvnw clean package
          cd ..

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and validate container
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 25

      - name: Check if Spring Boot is running
        run: |
          curl --fail http://localhost:8080 || exit 1

      - name: Stop and remove containers
        run: docker-compose down