name: Docker Validation

on:
  push:
    branches:
      - main
      - developer

jobs:
  validate-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set permissions for Maven Wrapper
        run: chmod +x ./backend/mvnw

      - name: Clear Maven Cache
        run: ./mvnw clean install -U

      - name: Build JAR file
        run: |
          cd backend
          ./mvnw clean package
          cd ..

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and validate container
        run: |
          docker compose -f docker-compose.yml up --build --exit-code-from backend --abort-on-container-exit